# Generated by Django 5.2.8 on 2025-12-09 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account for this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Staff',
                'verbose_name_plural': 'School Staff',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, help_text='When this assignment began', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When this assignment ended (null = currently active)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(help_text='Job title/role at this school', on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='integrations.emisjobtitle')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School where staff is assigned', on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='integrations.emisschool')),
                ('school_staff', models.ForeignKey(help_text='Staff member being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'School Staff Assignment',
                'verbose_name_plural': 'School Staff Assignments',
                'ordering': ['school_staff_id', 'school_id', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='school_staff_members', through='core.SchoolStaffAssignment', to='integrations.emisschool'),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(blank=True, help_text='Organization or department (e.g., Ministry of Education, District Office)', max_length=255)),
                ('position_title', models.CharField(blank=True, help_text='Job title or position within the organization', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account for this system user', on_delete=django.db.models.deletion.CASCADE, related_name='system_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(help_text='Official teacher registration/license ID', max_length=50, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, help_text='e.g., Bachelor of Education, Master of Science, etc.', max_length=255)),
                ('specialization', models.TextField(blank=True, help_text='Teaching specialization/subject areas')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Total years of teaching experience', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this teacher currently registered/active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('school_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['school_staff__user__last_name', 'school_staff__user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolstaffassignment',
            index=models.Index(fields=['start_date', 'end_date'], name='core_school_start_d_a01bc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolstaffassignment',
            constraint=models.UniqueConstraint(fields=('school_staff', 'school', 'start_date', 'end_date'), name='uq_school_staff_assignment'),
        ),
    ]
