# Generated by Django 5.2.8 on 2025-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='staff_type',
            field=models.CharField(choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff')], default='non_teaching', help_text='Type of staff member - teaching or non-teaching', max_length=20),
        ),
    ]
