# Generated by Django 5.2.8 on 2025-12-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_staff_type_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
