# Generated by Django 5.2.8 on 2025-12-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_teacher'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaffassignment',
            name='job_title',
            field=models.ForeignKey(help_text='Job title/role at this school', on_delete=django.db.models.deletion.PROTECT, related_name='job_title_assignments', to='integrations.emisjobtitle'),
        ),
    ]
