# Generated by Django 5.2.8 on 2026-01-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schoolstaffassignment_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=100),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='National ID number'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('expired', 'Expired')], help_text='Registration status (only applicable for teaching staff)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='registration_valid_until',
            field=models.DateField(blank=True, help_text='Date when current registration expires', null=True),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='teaching_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teaching certificate number'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of teaching experience'),
        ),
    ]
