# Generated by Django 5.2.8 on 2026-01-21 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolstaff_address_line_1_and_more'),
        ('integrations', '0003_emiseducationlevel_emisgender_emisisland_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('code', models.CharField(help_text='Unique institution code', max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Institution name', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether this institution is available for selection')),
            ],
            options={
                'verbose_name': 'Education Institution',
                'verbose_name_plural': 'Education Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='business_address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business address line 1'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='business_address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business address line 2'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='business_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business city'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='business_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business province'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='gender_emis',
            field=models.ForeignKey(blank=True, help_text='Gender from EMIS lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_staff', to='integrations.emisgender', verbose_name='Gender (EMIS)'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='home_island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_staff', to='integrations.emisisland', verbose_name='Home island'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_staff', to='integrations.emismaritalstatus', verbose_name='Marital status'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='nearby_school',
            field=models.ForeignKey(blank=True, help_text='Nearest school to residential address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_staff', to='integrations.emisschool', verbose_name='Nearest school'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='phone_home',
            field=models.CharField(blank=True, max_length=30, verbose_name='Home phone'),
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=10, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile phone'),
        ),
        migrations.CreateModel(
            name='StaffEducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(help_text='Name of the educational institution', max_length=255)),
                ('program_name', models.CharField(blank=True, help_text='Name of the program or course', max_length=255)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of completion')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the program', null=True)),
                ('duration_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months')], default='years', max_length=10)),
                ('completed', models.BooleanField(default=True, help_text='Whether the program was completed')),
                ('percentage_progress', models.PositiveIntegerField(blank=True, help_text='Progress percentage if not completed (0-100)', null=True)),
                ('comment', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_education_major_records', to='integrations.emissubject', verbose_name='Major subject')),
                ('minor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_education_minor_records', to='integrations.emissubject', verbose_name='Minor subject')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_education_records', to='integrations.emisteacherqual', verbose_name='Qualification type')),
                ('school_staff', models.ForeignKey(help_text='Staff member this education record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'Staff Education Record',
                'verbose_name_plural': 'Staff Education Records',
                'ordering': ['-completion_year', 'institution_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('provider_institution', models.CharField(help_text='Name of the training provider', max_length=255)),
                ('title', models.CharField(help_text='Title of the training or PD program', max_length=255)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of completion')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the training', null=True)),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10)),
                ('effective_date', models.DateField(blank=True, help_text='When certification becomes effective', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='When certification expires', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_training_records', to='integrations.emisteacherpdfocus', verbose_name='Focus area')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_training_records', to='integrations.emisteacherpdformat', verbose_name='Delivery format')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('school_staff', models.ForeignKey(help_text='Staff member this training record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'Staff Training Record',
                'verbose_name_plural': 'Staff Training Records',
                'ordering': ['-completion_year', 'title'],
            },
        ),
    ]
