# Generated by Django 5.2.8 on 2026-01-21 18:36
# Modified to handle CharField -> ForeignKey conversion with existing data

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Data migration: Convert existing text nationality values to FK references.
    Empty strings become NULL since the field is nullable.
    """
    SchoolStaff = apps.get_model('core', 'SchoolStaff')
    EmisNationality = apps.get_model('integrations', 'EmisNationality')

    for staff in SchoolStaff.objects.all():
        if staff.nationality_old and staff.nationality_old.strip():
            # Try to find matching nationality by label or code
            nationality = EmisNationality.objects.filter(
                models.Q(label__iexact=staff.nationality_old.strip()) |
                models.Q(code__iexact=staff.nationality_old.strip())
            ).first()
            if nationality:
                staff.nationality = nationality
                staff.save(update_fields=['nationality'])


def backwards_func(apps, schema_editor):
    """
    Reverse: Convert FK nationality back to text.
    """
    SchoolStaff = apps.get_model('core', 'SchoolStaff')

    for staff in SchoolStaff.objects.all():
        if staff.nationality:
            staff.nationality_old = staff.nationality.label
            staff.save(update_fields=['nationality_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_educationinstitution_and_more'),
        ('integrations', '0005_emisnationality'),
    ]

    operations = [
        # Step 1: Rename old CharField to nationality_old
        migrations.RenameField(
            model_name='schoolstaff',
            old_name='nationality',
            new_name='nationality_old',
        ),
        # Step 2: Add new FK field
        migrations.AddField(
            model_name='schoolstaff',
            name='nationality',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='school_staff',
                to='integrations.emisnationality',
                verbose_name='Nationality',
            ),
        ),
        # Step 3: Run data migration
        migrations.RunPython(forwards_func, backwards_func),
        # Step 4: Remove old field
        migrations.RemoveField(
            model_name='schoolstaff',
            name='nationality_old',
        ),
    ]
