# Generated by Django 5.2.8 on 2026-01-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schoolstaff_nationality'),
        ('integrations', '0005_emisnationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftrainingrecord',
            name='focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_training_records_focus', to='integrations.emisteacherpdfocus', verbose_name='Focus area'),
        ),
        migrations.AlterField(
            model_name='stafftrainingrecord',
            name='title',
            field=models.ForeignKey(help_text='Title of the training or PD program', on_delete=django.db.models.deletion.PROTECT, related_name='staff_training_records', to='integrations.emisteacherpdtype', verbose_name='Training title'),
        ),
    ]
