# Generated by Django 5.2.8 on 2026-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_schoolstaff_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstaff',
            name='teaching_certificate_number',
        ),
        migrations.AddField(
            model_name='schoolstaff',
            name='teacher_payroll_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teacher Payroll Number (PF Number)'),
        ),
    ]
