# Generated by Django 5.2.8 on 2026-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_schoolstaff_teaching_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='teacher_registration_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique registration number (format: TR26-A7K9-C)', max_length=20, null=True, unique=True, verbose_name='Teacher Registration Number'),
        ),
    ]
