# Generated by Django 5.2.8 on 2026-02-07 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schoolstaff_teacher_registration_number'),
        ('integrations', '0005_emisnationality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTeachingDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='School assignment this duty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_duties', to='core.schoolstaffassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_teaching_duties', to='integrations.emissubject', verbose_name='Subject taught')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_teaching_duties', to='integrations.emisclasslevel', verbose_name='Year/Class level')),
            ],
            options={
                'verbose_name': 'Staff Teaching Duty',
                'verbose_name_plural': 'Staff Teaching Duties',
                'ordering': ['assignment', 'year_level', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'year_level', 'subject'), name='uq_staff_teaching_duty')],
            },
        ),
    ]
