# Generated by Django 5.2.8 on 2026-02-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staffteachingduty'),
        ('integrations', '0006_emisteacherregistrationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='teacher_registration_status',
            field=models.ForeignKey(blank=True, help_text='Registration status from EMIS lookup (e.g., Registered, Provisional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_staff', to='integrations.emisteacherregistrationstatus', verbose_name='Teacher Registration Status'),
        ),
    ]
