# Generated by Django 5.2.8 on 2026-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schoolstaff_teacher_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaff',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], help_text='Registration status (only applicable for teaching staff)', max_length=20, null=True),
        ),
    ]
