# Generated by Django 5.2.8 on 2026-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_schoolstaff_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaff',
            name='registration_valid_until',
            field=models.DateTimeField(blank=True, help_text='Datetime when current registration expires', null=True),
        ),
    ]
