# Generated by Django 5.2.8 on 2026-02-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_schoolstaff_registration_valid_until'),
        ('integrations', '0007_emisteacherregistrationstatus_validity_unit_and_more'),
    ]

    operations = [
        # 1. Drop the legacy CharField column (contains empty strings, not FK refs)
        migrations.RemoveField(
            model_name='schoolstaff',
            name='gender',
        ),
        # 2. Rename the real FK column gender_emis -> gender
        migrations.RenameField(
            model_name='schoolstaff',
            old_name='gender_emis',
            new_name='gender',
        ),
    ]
