# Generated by Django 5.2.8 on 2026-02-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_schoolstaff_gender_emis_and_more'),
        ('integrations', '0007_emisteacherregistrationstatus_validity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaff',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_staff', to='integrations.emisgender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='teacher_payroll_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teacher Payroll Number'),
        ),
    ]
