# Generated by Django 5.2.8 on 2026-02-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_schoolstaff_gender_and_more'),
        ('integrations', '0007_emisteacherregistrationstatus_validity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaffassignment',
            name='teacher_level_type',
            field=models.ForeignKey(blank=True, help_text='Education level (Primary/JSS/SSS) for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='integrations.emiseducationlevel'),
        ),
    ]
