# Generated by Django 5.2.8 on 2026-03-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_schoolstaffassignment_teacher_level_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaff',
            name='registration_application_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ready_for_approval', 'Ready for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], help_text='Registration application status (only applicable for teaching staff)', max_length=20, null=True),
        ),
    ]
