# Generated by Django 5.2.8 on 2026-03-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_schoolstaff_registration_application_status'),
        ('integrations', '0008_emisteacherlinktype_needs_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffeducationrecord',
            name='major2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_education_major2_records', to='integrations.emissubject', verbose_name='Major subject 2'),
        ),
        migrations.AddField(
            model_name='staffeducationrecord',
            name='minor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_education_minor2_records', to='integrations.emissubject', verbose_name='Minor subject 2'),
        ),
        migrations.AddField(
            model_name='stafftrainingrecord',
            name='general_focus_area',
            field=models.CharField(blank=True, help_text='General area of focus for this training', max_length=255, verbose_name='General Focus Area'),
        ),
        migrations.AlterField(
            model_name='stafftrainingrecord',
            name='focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_training_records', to='integrations.emisteacherpdfocus', verbose_name='KTC Focus Area'),
        ),
    ]
