# Generated by Django 5.2.8 on 2026-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_staffeducationrecord_major2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftrainingrecord',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='days', max_length=10),
        ),
    ]
