# Generated by Django 5.2.14 on 2026-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_stafftrainingrecord_duration_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaff',
            name='registration_granted_at',
            field=models.DateTimeField(blank=True, help_text='Datetime the current registration was granted (approval/renewal). registration_valid_until is computed from this. May be back/post-dated by the reviewer; defaults to the moment of the approval decision.', null=True),
        ),
        migrations.AlterField(
            model_name='schoolstaff',
            name='registration_application_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ready_for_approval', 'Ready for Decision Approval/Rejection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], help_text='Registration application status (only applicable for teaching staff)', max_length=20, null=True),
        ),
    ]
