# Generated by Django 5.2.14 on 2026-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_schoolstaff_registration_granted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image (PNG with transparent background recommended). Overlaid on registration certificates when this user is the signatory.', null=True, upload_to='signatures/'),
        ),
    ]
