# Generated by Django 5.2.14 on 2026-06-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_schoolstaff_highest_qualification'),
        ('integrations', '0008_emisteacherlinktype_needs_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstaffassignment',
            name='employment_status',
            field=models.ForeignKey(blank=True, help_text='Employment status (e.g. permanent/temporary) for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='integrations.emisteacherstatus'),
        ),
    ]
