# Generated by Django 5.2.14 on 2026-06-17 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_schoolstaffassignment_employment_status'),
        ('integrations', '0008_emisteacherlinktype_needs_renewal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffteachingduty',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject taught (JSS/SSS only; blank for primary teachers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_teaching_duties', to='integrations.emissubject', verbose_name='Subject taught'),
        ),
        migrations.AddConstraint(
            model_name='staffteachingduty',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('assignment', 'year_level'), name='uq_staff_teaching_duty_no_subject'),
        ),
    ]
