# Generated by Django 5.2.8 on 2026-01-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisSubject',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['label'],
            },
        ),
    ]
