# Generated by Django 5.2.8 on 2026-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_emis_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisEducationLevel',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisGender',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisIsland',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Island',
                'verbose_name_plural': 'Islands',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EmisMaritalStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherLinkType',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher Link Type',
                'verbose_name_plural': 'Teacher Link Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherPdFocus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher PD Focus',
                'verbose_name_plural': 'Teacher PD Focuses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherPdFormat',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher PD Format',
                'verbose_name_plural': 'Teacher PD Formats',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherPdType',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher PD Type',
                'verbose_name_plural': 'Teacher PD Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherQual',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher Qualification',
                'verbose_name_plural': 'Teacher Qualifications',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmisTeacherStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher Status',
                'verbose_name_plural': 'Teacher Statuses',
                'ordering': ['code'],
            },
        ),
    ]
