# Generated by Django 5.2.8 on 2026-01-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_emiseducationlevel_emisgender_emisisland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisclasslevel',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emiseducationlevel',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisgender',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisisland',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisjobtitle',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emismaritalstatus',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emissubject',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherlinktype',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherpdfocus',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherpdformat',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherpdtype',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherqual',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emisteacherstatus',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emiswarehouseyear',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
