# Generated by Django 5.2.8 on 2026-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_emisclasslevel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisNationality',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['label'],
            },
        ),
    ]
