# Generated by Django 5.2.8 on 2026-02-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emisnationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisTeacherRegistrationStatus',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher Registration Status',
                'verbose_name_plural': 'Teacher Registration Statuses',
                'ordering': ['code'],
            },
        ),
    ]
