# Generated by Django 5.2.8 on 2026-02-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_emisteacherregistrationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisteacherregistrationstatus',
            name='validity_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('years', 'Years')], default='', help_text='Unit type for the validity period', max_length=16),
        ),
        migrations.AddField(
            model_name='emisteacherregistrationstatus',
            name='validity_value',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units for the validity period', null=True),
        ),
    ]
