# Generated by Django 5.2.8 on 2026-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_emisteacherregistrationstatus_validity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisteacherlinktype',
            name='needs_renewal',
            field=models.BooleanField(default=False, help_text='Whether documents of this type need periodic renewal'),
        ),
    ]
