# Generated by Django 5.2.8 on 2025-12-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Teacher Registration app',
                'verbose_name_plural': 'Teacher Registration app',
                'permissions': (('access_teacher_registration', 'Can access the Teacher Registration app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
