# Generated by Django 5.2.8 on 2025-12-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0001_initial'),
    ]

    operations = [
    ]
