# Generated by Django 5.2.8 on 2025-12-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0002_remove_permissions_anchor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionsAnchor',
        ),
    ]
