# Generated by Django 5.2.8 on 2026-01-15 23:37

import django.db.models.deletion
import teacher_registration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_schoolstaff_address_line_1_and_more'),
        ('integrations', '0001_initial'),
        ('teacher_registration', '0003_delete_permissionsanchor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('registration_type', models.CharField(choices=[('initial', 'Initial Registration'), ('renewal', 'Renewal')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('national_id_number', models.CharField(blank=True, max_length=50, verbose_name='National ID number')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('teaching_certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Teaching certificate number')),
                ('highest_qualification', models.CharField(blank=True, choices=[('high_school', 'High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of teaching experience')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the registration was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True, help_text='Comments from the reviewer (visible to applicant)')),
                ('approved_staff_profile', models.ForeignKey(blank=True, help_text='Link to SchoolStaff created on approval (audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_history', to='core.schoolstaff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('preferred_job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.emisjobtitle', verbose_name='Preferred position')),
                ('preferred_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_preferences', to='integrations.emisschool', verbose_name='Preferred school')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User submitting this registration', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Registration',
                'verbose_name_plural': 'Teacher Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('birth_certificate', 'Birth Certificate'), ('teaching_certificate', 'Teaching Certificate'), ('degree_certificate', 'Degree Certificate'), ('transcript', 'Academic Transcript'), ('photo', 'Passport Photo'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=teacher_registration.models.registration_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, help_text='Optional description or notes', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('school_staff', models.ForeignKey(blank=True, help_text='Staff profile this document belongs to (after approval)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.schoolstaff')),
                ('registration', models.ForeignKey(blank=True, help_text='Registration this document belongs to (while pending)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teacher_registration.teacherregistration')),
            ],
            options={
                'verbose_name': 'Registration Document',
                'verbose_name_plural': 'Registration Documents',
                'ordering': ['document_type', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('registration__isnull', False), ('school_staff__isnull', True)), models.Q(('registration__isnull', True), ('school_staff__isnull', False)), _connector='OR'), name='document_single_owner')],
            },
        ),
    ]
