# Generated by Django 5.2.8 on 2026-01-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Name of the field that changed (e.g., 'status')", max_length=100)),
                ('old_value', models.CharField(blank=True, help_text='Previous value (empty for creation)', max_length=255)),
                ('new_value', models.CharField(blank=True, help_text='New value after the change', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When this change occurred')),
                ('notes', models.TextField(blank=True, help_text='Optional context or reason for the change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_changes', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(help_text='Registration this change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='teacher_registration.teacherregistration')),
            ],
            options={
                'verbose_name': 'Registration Change Log',
                'verbose_name_plural': 'Registration Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['registration', '-changed_at'], name='teacher_reg_registr_81e77c_idx')],
            },
        ),
    ]
