# Generated by Django 5.2.8 on 2026-01-21 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_emiseducationlevel_emisgender_emisisland_and_more'),
        ('teacher_registration', '0005_registration_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdocument',
            name='doc_date',
            field=models.DateField(blank=True, help_text='Date associated with the document (e.g., issue date)', null=True, verbose_name='Document date'),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='doc_description',
            field=models.TextField(blank=True, verbose_name='Document description'),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='doc_link_type',
            field=models.ForeignKey(blank=True, help_text='Document type from EMIS lookup (replaces hardcoded document_type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='integrations.emisteacherlinktype', verbose_name='Document link type'),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='doc_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='doc_type',
            field=models.CharField(blank=True, help_text='Computed file extension (e.g., pdf, jpg)', max_length=20, verbose_name='File type'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='business_address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business address line 1'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='business_address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business address line 2'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='business_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business city'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='business_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business province'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='gender_emis',
            field=models.ForeignKey(blank=True, help_text='Gender from EMIS lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='integrations.emisgender', verbose_name='Gender (EMIS)'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='home_island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='integrations.emisisland', verbose_name='Home island'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='integrations.emismaritalstatus', verbose_name='Marital status'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='nearby_school',
            field=models.ForeignKey(blank=True, help_text='Nearest school to residential address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_registrations', to='integrations.emisschool', verbose_name='Nearest school'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='phone_home',
            field=models.CharField(blank=True, max_length=30, verbose_name='Home phone'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='teacher_category',
            field=models.CharField(choices=[('new', 'New Teacher'), ('current', 'Current Teacher')], default='new', help_text='Determines which form sections are displayed', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=10, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile phone'),
        ),
        migrations.CreateModel(
            name='ClaimedSchoolAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, help_text='When this appointment started (maps to SchoolStaffAssignment.start_date)', null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of experience')),
                ('class_type', models.CharField(blank=True, choices=[('single', 'Single-grade'), ('multi', 'Multi-grade')], help_text='Single-grade or Multi-grade (Primary teachers only)', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_island_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_appointments', to='integrations.emisisland', verbose_name='Island/Station')),
                ('current_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_appointments', to='integrations.emisschool', verbose_name='Current school')),
                ('employment_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_appointments', to='integrations.emisjobtitle', verbose_name='Position/Role')),
                ('employment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_appointments', to='integrations.emisteacherstatus', verbose_name='Employment status')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(help_text='Registration this appointment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='claimed_appointments', to='teacher_registration.teacherregistration')),
                ('teacher_level_type', models.ForeignKey(help_text='Education level (Primary, JSS, SSS)', on_delete=django.db.models.deletion.PROTECT, related_name='claimed_appointments', to='integrations.emiseducationlevel', verbose_name='Teacher level')),
            ],
            options={
                'verbose_name': 'Claimed School Appointment',
                'verbose_name_plural': 'Claimed School Appointments',
                'ordering': ['registration', 'current_school'],
            },
        ),
        migrations.CreateModel(
            name='ClaimedDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_duties', to='integrations.emissubject', verbose_name='Subject taught')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_duties', to='integrations.emisclasslevel', verbose_name='Year/Class level')),
                ('appointment', models.ForeignKey(help_text='School appointment this duty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='claimed_duties', to='teacher_registration.claimedschoolappointment')),
            ],
            options={
                'verbose_name': 'Claimed Duty',
                'verbose_name_plural': 'Claimed Duties',
                'ordering': ['appointment', 'year_level', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(help_text='Name of the educational institution', max_length=255)),
                ('program_name', models.CharField(blank=True, help_text='Name of the program or course', max_length=255)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of completion')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the program', null=True)),
                ('duration_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months')], default='years', max_length=10)),
                ('completed', models.BooleanField(default=True, help_text='Whether the program was completed')),
                ('percentage_progress', models.PositiveIntegerField(blank=True, help_text='Progress percentage if not completed (0-100)', null=True)),
                ('comment', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_major_records', to='integrations.emissubject', verbose_name='Major subject')),
                ('minor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_minor_records', to='integrations.emissubject', verbose_name='Minor subject')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_records', to='integrations.emisteacherqual', verbose_name='Qualification type')),
                ('registration', models.ForeignKey(help_text='Registration this education record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='teacher_registration.teacherregistration')),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'ordering': ['-completion_year', 'institution_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('provider_institution', models.CharField(help_text='Name of the training provider', max_length=255)),
                ('title', models.CharField(help_text='Title of the training or PD program', max_length=255)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of completion')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the training', null=True)),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10)),
                ('effective_date', models.DateField(blank=True, help_text='When certification becomes effective', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='When certification expires', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='integrations.emisteacherpdfocus', verbose_name='Focus area')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='integrations.emisteacherpdformat', verbose_name='Delivery format')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(help_text='Registration this training record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='teacher_registration.teacherregistration')),
            ],
            options={
                'verbose_name': 'Training Record',
                'verbose_name_plural': 'Training Records',
                'ordering': ['-completion_year', 'title'],
            },
        ),
    ]
