# Generated by Django 5.2.8 on 2026-01-21 18:36
# Modified to handle CharField -> ForeignKey conversion with existing data

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Data migration: Convert existing text nationality values to FK references.
    Empty strings become NULL since the field is nullable.
    """
    TeacherRegistration = apps.get_model('teacher_registration', 'TeacherRegistration')
    EmisNationality = apps.get_model('integrations', 'EmisNationality')

    for registration in TeacherRegistration.objects.all():
        if registration.nationality_old and registration.nationality_old.strip():
            # Try to find matching nationality by label or code
            nationality = EmisNationality.objects.filter(
                models.Q(label__iexact=registration.nationality_old.strip()) |
                models.Q(code__iexact=registration.nationality_old.strip())
            ).first()
            if nationality:
                registration.nationality = nationality
                registration.save(update_fields=['nationality'])


def backwards_func(apps, schema_editor):
    """
    Reverse: Convert FK nationality back to text.
    """
    TeacherRegistration = apps.get_model('teacher_registration', 'TeacherRegistration')

    for registration in TeacherRegistration.objects.all():
        if registration.nationality:
            registration.nationality_old = registration.nationality.label
            registration.save(update_fields=['nationality_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emisnationality'),
        ('teacher_registration', '0006_registrationdocument_doc_date_and_more'),
    ]

    operations = [
        # Step 1: Rename old CharField to nationality_old
        migrations.RenameField(
            model_name='teacherregistration',
            old_name='nationality',
            new_name='nationality_old',
        ),
        # Step 2: Add new FK field
        migrations.AddField(
            model_name='teacherregistration',
            name='nationality',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='registrations',
                to='integrations.emisnationality',
                verbose_name='Nationality',
            ),
        ),
        # Step 3: Run data migration
        migrations.RunPython(forwards_func, backwards_func),
        # Step 4: Remove old field
        migrations.RemoveField(
            model_name='teacherregistration',
            name='nationality_old',
        ),
    ]
