# Generated by Django 5.2.8 on 2026-01-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emisnationality'),
        ('teacher_registration', '0007_alter_teacherregistration_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='title',
            field=models.ForeignKey(help_text='Title of the training or PD program', on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='integrations.emisteacherpdtype', verbose_name='Training title'),
        ),
    ]
