# Generated by Django 5.2.8 on 2026-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0008_alter_trainingrecord_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='title',
            field=models.CharField(help_text='Title of the training or PD program', max_length=255),
        ),
    ]
