# Generated by Django 5.2.8 on 2026-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0009_alter_trainingrecord_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherregistration',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='business_address_line_1',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='business_address_line_2',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='business_province',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='province',
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='business_address',
            field=models.TextField(blank=True, help_text='Full business/work address (optional)', verbose_name='Business address'),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='residential_address',
            field=models.TextField(blank=True, help_text='Full residential/home address', verbose_name='Residential address'),
        ),
    ]
