# Generated by Django 5.2.8 on 2026-01-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emisnationality'),
        ('teacher_registration', '0011_remove_teacherregistration_teaching_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationdocument',
            options={'ordering': ['doc_link_type', 'created_at'], 'verbose_name': 'Registration Document', 'verbose_name_plural': 'Registration Documents'},
        ),
        migrations.RemoveField(
            model_name='registrationdocument',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_link_type',
            field=models.ForeignKey(help_text='Document type from EMIS lookup', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='integrations.emisteacherlinktype', verbose_name='Document type'),
        ),
    ]
