# Generated by Django 5.2.8 on 2026-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0012_alter_registrationdocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdocument',
            name='description',
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_description',
            field=models.TextField(blank=True, help_text='Optional description or notes', verbose_name='Document description'),
        ),
    ]
