# Generated by Django 5.2.8 on 2026-02-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0013_remove_registrationdocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedschoolappointment',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this appointment ended (maps to SchoolStaffAssignment.end_date). Leave blank for current appointments.', null=True),
        ),
    ]
