# Generated by Django 5.2.8 on 2026-02-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_emisteacherregistrationstatus_validity_unit_and_more'),
        ('teacher_registration', '0016_remove_teacherregistration_gender_emis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='integrations.emisgender', verbose_name='Gender'),
        ),
    ]
