# Generated by Django 5.2.8 on 2026-03-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0018_teacherregistration_checklist_applicant_birth_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='checklist_ready_for_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ready_for_approval', 'Ready for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
