# Generated by Django 5.2.8 on 2026-03-04 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_schoolstaff_registration_application_status'),
        ('teacher_registration', '0019_teacherregistration_checklist_ready_for_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCondition',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condition Type',
                'verbose_name_plural': 'Condition Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Free-form notes about this condition')),
                ('condition', models.ForeignKey(help_text='Condition type from local lookup', on_delete=django.db.models.deletion.PROTECT, related_name='registration_conditions', to='teacher_registration.lookupcondition', verbose_name='Condition type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, help_text='Registration this condition belongs to (while pending)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='teacher_registration.teacherregistration')),
                ('school_staff', models.ForeignKey(blank=True, help_text='Staff profile this condition belongs to (after approval)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.schoolstaff')),
            ],
            options={
                'verbose_name': 'Registration Condition',
                'verbose_name_plural': 'Registration Conditions',
                'ordering': ['condition', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('registration__isnull', False), ('school_staff__isnull', True)), models.Q(('registration__isnull', True), ('school_staff__isnull', False)), _connector='OR'), name='condition_single_owner')],
            },
        ),
    ]
