# Generated by Django 5.2.8 on 2026-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0021_educationrecord_major2_educationrecord_minor2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcondition',
            name='deadline',
            field=models.DateField(blank=True, help_text='Optional deadline date for this condition to be met', null=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='days', max_length=10),
        ),
    ]
