# Generated by Django 5.2.14 on 2026-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0022_registrationcondition_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ready_for_approval', 'Ready for Decision Approval/Rejection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
