# Generated by Django 5.2.14 on 2026-05-19 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0023_alter_teacherregistration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='signatory',
            field=models.ForeignKey(blank=True, help_text="Official who signs the registration certificate. Chosen at approval from the 'Registration Signatories' group.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
