# Generated by Django 5.2.14 on 2026-06-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0024_teacherregistration_signatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('advanced_diploma', 'Advanced Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=100),
        ),
    ]
