# Generated by Django 5.2.14 on 2026-06-10 01:11

import teacher_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_registration', '0025_alter_teacherregistration_highest_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdocument',
            name='cropped_file',
            field=models.ImageField(blank=True, help_text='Normalized passport photo produced by the in-app crop/rotate tool. When present, the profile and certificate display this instead of the original upload (which may be a PDF or an uncropped scan).', null=True, upload_to=teacher_registration.models.registration_upload_path),
        ),
    ]
