# Generated by Django 5.2.14 on 2026-06-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_emisteacherlinktype_needs_renewal'),
        ('teacher_registration', '0026_registrationdocument_cropped_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedduty',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject taught (JSS/SSS only; blank for primary teachers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_duties', to='integrations.emissubject', verbose_name='Subject taught'),
        ),
    ]
